version: '3'
services:
  app:
    build: .
    container_name: td_be_test_task_app
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - database
    command: ["bin/console", "doctrine:migrations:migrate", "--no-interaction"]

  database:
    image: mariadb:10.1
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - ./data/db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: [ '--default-authentication-plugin=mysql_native_password' ]

volumes:
  data: